### ISSUE TITLE
weighted averaging check wrong

### ISSUE THREAD

**Issue by ozancaglayan** [SimulTrans-demo/STACL#1]
Hello,

In the following line, `is_weight_ave` check is inversed i.e. corpus mean is actually the weighted average and vice-versa.

https://github.com/SimulTrans-demo/STACL/blob/111605999cd8740ac182e14c835418cca676bcf2/metricAL.py#L64

**Comment by SimulTrans-demo** [comment]
Thanks for pointing out this bug. It's been fixed.

**Comment by ozancaglayan** [comment]
Thanks. Are the reported results in the paper were actually weighted ones then?

**Comment by SimulTrans-demo** [comment]
Hi Ozan,

Thanks for your interest in our paper. And sorry for the bug in the open
source code.
To be clarified, the corpus level AL reported in the paper is just average,
*not* weighted.

Best,

STACL team
